### ISSUE TITLE
Laravel Elixer 3.0

### ISSUE THREAD

**Issue by Thellior** [parsnick/laravel-elixir-bowerbundle#1]
Hi, I really like your plugin and use it daily but i had one question.
Is this going to be compatible with 3.0 :)

Cheers

**Comment by parsnick** [comment]
@Thellior thanks for opening this.

I've just pushed a 2.0 release to work with Elixir 3.0. There's a couple of breaking changes to the API, detailed in the [release notes](https://github.com/parsnick/laravel-elixir-bowerbundle/releases/tag/v2.0.0).
